/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['h1[_ngcontent-%COMP%] {\n    color: green;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2JvdWVsbGV0dGUvZ2l0L01peHBvTHVjaExlYXJuL0FuZ3VsYXI0L0N1c3RvbS9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYm91ZWxsZXR0ZS9naXQvTWl4cG9MdWNoTGVhcm4vQW5ndWxhcjQvQ3VzdG9tL3NyYy9hcHAvdXNlcnMvdXNlcnMuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
