/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './users.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './users.component';
const styles_UsersComponent:any[] = [import0.styles];
export const RenderType_UsersComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_UsersComponent,
  data: {}
}
);
export function View_UsersComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Users Component here!']))
  ]
  ,(null as any),(null as any));
}
function View_UsersComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_UsersComponent_0,RenderType_UsersComponent)),
    import1.ɵdid(49152,(null as any),0,import2.UsersComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UsersComponentNgFactory:import1.ComponentFactory<import2.UsersComponent> = import1.ɵccf('ng-component',import2.UsersComponent,View_UsersComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2JvdWVsbGV0dGUvZ2l0L01peHBvTHVjaExlYXJuL0FuZ3VsYXI0L0N1c3RvbS9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9ib3VlbGxldHRlL2dpdC9NaXhwb0x1Y2hMZWFybi9Bbmd1bGFyNC9DdXN0b20vc3JjL2FwcC91c2Vycy91c2Vycy5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9ib3VlbGxldHRlL2dpdC9NaXhwb0x1Y2hMZWFybi9Bbmd1bGFyNC9DdXN0b20vc3JjL2FwcC91c2Vycy91c2Vycy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2JvdWVsbGV0dGUvZ2l0L01peHBvTHVjaExlYXJuL0FuZ3VsYXI0L0N1c3RvbS9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC50cy5Vc2Vyc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5Vc2VycyBDb21wb25lbnQgaGVyZSE8L2gxPiIsIjxuZy1jb21wb25lbnQ+PC9uZy1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJOzs7Ozs7SUNBSjtnQkFBQTs7OzsifQ==
