version: '2'

services:
  db:
    container_name: db
    image: mongo
    build:
      context: .
      dockerfile: mongoDockerFile
    ports:
      - "27017:27017"
#    volumes:
#      - ../mixpo.com/db:/usr/src/app/db
#      - /tmp/dbBackup:/tmp/dbBackup

  node:
    container_name: mynode
#    image: ubertoad2.mixpo.com:5000/obsidian
    build:
      context: .
      dockerfile: mynode
    command: node /home/mixpo/app.js
    ports:
     - "1337:1337"
    volumes:
     - .:/home/mixpo/
    links:
     - db
    depends_on:
     - db
