/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './app.module';
import * as import2 from '@angular/router';
import * as import3 from '@angular/common';
import * as import4 from './app-routing.module';
import * as import5 from '@angular/platform-browser';
import * as import6 from './home.component.ngfactory';
import * as import7 from './app.component.ngfactory';
import * as import8 from './home.component';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _ɵa_0:any;
  _ErrorHandler_1:any;
  _ɵg_2:import2.ɵg;
  _NgProbeToken_3:any[];
  _APP_INITIALIZER_4:any[];
  _ApplicationInitStatus_5:import0.ApplicationInitStatus;
  _ɵf_6:import0.ɵf;
  _ApplicationRef_7:any;
  _UrlSerializer_8:import2.DefaultUrlSerializer;
  _RouterOutletMap_9:import2.RouterOutletMap;
  _ROUTER_CONFIGURATION_10:any;
  _LocationStrategy_11:any;
  _Location_12:import3.Location;
  _Compiler_13:import0.Compiler;
  _NgModuleFactoryLoader_14:import0.SystemJsNgModuleLoader;
  _ROUTES_15:any[];
  _Router_16:any;
  _RouterModule_17:import2.RouterModule;
  _AppRoutingModule_18:import4.AppRoutingModule;
  _CommonModule_19:import3.CommonModule;
  _ApplicationModule_20:import0.ApplicationModule;
  _BrowserModule_21:import5.BrowserModule;
  _AppModule_22:import1.AppModule;
  __ActivatedRoute_23:any;
  __NoPreloading_24:import2.NoPreloading;
  __PreloadingStrategy_25:any;
  __RouterPreloader_26:import2.RouterPreloader;
  __PreloadAllModules_27:import2.PreloadAllModules;
  __ROUTER_INITIALIZER_28:any;
  __APP_BOOTSTRAP_LISTENER_29:any[];
  __LOCALE_ID_30:any;
  __NgLocalization_31:import3.NgLocaleLocalization;
  __APP_ID_32:any;
  __IterableDiffers_33:any;
  __KeyValueDiffers_34:any;
  __DomSanitizer_35:import5.ɵe;
  __Sanitizer_36:any;
  __HAMMER_GESTURE_CONFIG_37:import5.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_38:any[];
  __EventManager_39:import5.EventManager;
  __ɵDomSharedStylesHost_40:import5.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_41:import5.ɵDomRendererFactory2;
  __RendererFactory2_42:any;
  __ɵSharedStylesHost_43:any;
  __Testability_44:import0.Testability;
  __Meta_45:import5.Meta;
  __Title_46:import5.Title;
  constructor(parent:import0.Injector) {
    super(parent,[
      import6.HomeComponentNgFactory,
      import7.AppComponentNgFactory
    ]
    ,[import7.AppComponentNgFactory]);
  }
  get _ActivatedRoute_23():any {
    if ((this.__ActivatedRoute_23 == null)) { (this.__ActivatedRoute_23 = import2.ɵf(this._Router_16)); }
    return this.__ActivatedRoute_23;
  }
  get _NoPreloading_24():import2.NoPreloading {
    if ((this.__NoPreloading_24 == null)) { (this.__NoPreloading_24 = new import2.NoPreloading()); }
    return this.__NoPreloading_24;
  }
  get _PreloadingStrategy_25():any {
    if ((this.__PreloadingStrategy_25 == null)) { (this.__PreloadingStrategy_25 = this._NoPreloading_24); }
    return this.__PreloadingStrategy_25;
  }
  get _RouterPreloader_26():import2.RouterPreloader {
    if ((this.__RouterPreloader_26 == null)) { (this.__RouterPreloader_26 = new import2.RouterPreloader(this._Router_16,this._NgModuleFactoryLoader_14,this._Compiler_13,this,this._PreloadingStrategy_25)); }
    return this.__RouterPreloader_26;
  }
  get _PreloadAllModules_27():import2.PreloadAllModules {
    if ((this.__PreloadAllModules_27 == null)) { (this.__PreloadAllModules_27 = new import2.PreloadAllModules()); }
    return this.__PreloadAllModules_27;
  }
  get _ROUTER_INITIALIZER_28():any {
    if ((this.__ROUTER_INITIALIZER_28 == null)) { (this.__ROUTER_INITIALIZER_28 = import2.ɵi(this._ɵg_2)); }
    return this.__ROUTER_INITIALIZER_28;
  }
  get _APP_BOOTSTRAP_LISTENER_29():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_29 == null)) { (this.__APP_BOOTSTRAP_LISTENER_29 = [this._ROUTER_INITIALIZER_28]); }
    return this.__APP_BOOTSTRAP_LISTENER_29;
  }
  get _LOCALE_ID_30():any {
    if ((this.__LOCALE_ID_30 == null)) { (this.__LOCALE_ID_30 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_30;
  }
  get _NgLocalization_31():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_31 == null)) { (this.__NgLocalization_31 = new import3.NgLocaleLocalization(this._LOCALE_ID_30)); }
    return this.__NgLocalization_31;
  }
  get _APP_ID_32():any {
    if ((this.__APP_ID_32 == null)) { (this.__APP_ID_32 = import0.ɵg()); }
    return this.__APP_ID_32;
  }
  get _IterableDiffers_33():any {
    if ((this.__IterableDiffers_33 == null)) { (this.__IterableDiffers_33 = import0.ɵl()); }
    return this.__IterableDiffers_33;
  }
  get _KeyValueDiffers_34():any {
    if ((this.__KeyValueDiffers_34 == null)) { (this.__KeyValueDiffers_34 = import0.ɵm()); }
    return this.__KeyValueDiffers_34;
  }
  get _DomSanitizer_35():import5.ɵe {
    if ((this.__DomSanitizer_35 == null)) { (this.__DomSanitizer_35 = new import5.ɵe(this.parent.get(import5.DOCUMENT))); }
    return this.__DomSanitizer_35;
  }
  get _Sanitizer_36():any {
    if ((this.__Sanitizer_36 == null)) { (this.__Sanitizer_36 = this._DomSanitizer_35); }
    return this.__Sanitizer_36;
  }
  get _HAMMER_GESTURE_CONFIG_37():import5.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_37 == null)) { (this.__HAMMER_GESTURE_CONFIG_37 = new import5.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_37;
  }
  get _EVENT_MANAGER_PLUGINS_38():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_38 == null)) { (this.__EVENT_MANAGER_PLUGINS_38 = [
      new import5.ɵDomEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵKeyEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵHammerGesturesPlugin(this.parent.get(import5.DOCUMENT),this._HAMMER_GESTURE_CONFIG_37)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_38;
  }
  get _EventManager_39():import5.EventManager {
    if ((this.__EventManager_39 == null)) { (this.__EventManager_39 = new import5.EventManager(this._EVENT_MANAGER_PLUGINS_38,this.parent.get(import0.NgZone))); }
    return this.__EventManager_39;
  }
  get _ɵDomSharedStylesHost_40():import5.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_40 == null)) { (this.__ɵDomSharedStylesHost_40 = new import5.ɵDomSharedStylesHost(this.parent.get(import5.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_40;
  }
  get _ɵDomRendererFactory2_41():import5.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_41 == null)) { (this.__ɵDomRendererFactory2_41 = new import5.ɵDomRendererFactory2(this._EventManager_39,this._ɵDomSharedStylesHost_40)); }
    return this.__ɵDomRendererFactory2_41;
  }
  get _RendererFactory2_42():any {
    if ((this.__RendererFactory2_42 == null)) { (this.__RendererFactory2_42 = this._ɵDomRendererFactory2_41); }
    return this.__RendererFactory2_42;
  }
  get _ɵSharedStylesHost_43():any {
    if ((this.__ɵSharedStylesHost_43 == null)) { (this.__ɵSharedStylesHost_43 = this._ɵDomSharedStylesHost_40); }
    return this.__ɵSharedStylesHost_43;
  }
  get _Testability_44():import0.Testability {
    if ((this.__Testability_44 == null)) { (this.__Testability_44 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_44;
  }
  get _Meta_45():import5.Meta {
    if ((this.__Meta_45 == null)) { (this.__Meta_45 = new import5.Meta(this.parent.get(import5.DOCUMENT))); }
    return this.__Meta_45;
  }
  get _Title_46():import5.Title {
    if ((this.__Title_46 == null)) { (this.__Title_46 = new import5.Title(this.parent.get(import5.DOCUMENT))); }
    return this.__Title_46;
  }
  createInternal():import1.AppModule {
    this._ɵa_0 = import2.ɵd(this.parent.get(import2.Router,(null as any)));
    this._ErrorHandler_1 = import5.ɵa();
    this._ɵg_2 = new import2.ɵg(this);
    this._NgProbeToken_3 = [import2.ɵb()];
    this._APP_INITIALIZER_4 = [
      import2.ɵh(this._ɵg_2),
      import0.ɵo,
      import5.ɵc(this.parent.get(import5.NgProbeToken,(null as any)),this._NgProbeToken_3)
    ]
    ;
    this._ApplicationInitStatus_5 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_4);
    this._ɵf_6 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_5);
    this._ApplicationRef_7 = this._ɵf_6;
    this._UrlSerializer_8 = new import2.DefaultUrlSerializer();
    this._RouterOutletMap_9 = new import2.RouterOutletMap();
    this._ROUTER_CONFIGURATION_10 = {};
    this._LocationStrategy_11 = import2.ɵc(this.parent.get(import3.PlatformLocation),this.parent.get(import3.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_10);
    this._Location_12 = new import3.Location(this._LocationStrategy_11);
    this._Compiler_13 = new import0.Compiler();
    this._NgModuleFactoryLoader_14 = new import0.SystemJsNgModuleLoader(this._Compiler_13,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
      this._ROUTES_15 = [[
        {
          path: '',
          component: import8.HomeComponent
        }
        ,
        {
          path: 'users',
          loadChildren: './users/users.module#UsersModule'
        }

      ]
    ];
    this._Router_16 = import2.ɵe(this._ApplicationRef_7,this._UrlSerializer_8,this._RouterOutletMap_9,this._Location_12,this,this._NgModuleFactoryLoader_14,this._Compiler_13,this._ROUTES_15,this._ROUTER_CONFIGURATION_10,this.parent.get(import2.UrlHandlingStrategy,(null as any)),this.parent.get(import2.RouteReuseStrategy,(null as any)));
    this._RouterModule_17 = new import2.RouterModule(this._ɵa_0,this._Router_16);
    this._AppRoutingModule_18 = new import4.AppRoutingModule();
    this._CommonModule_19 = new import3.CommonModule();
    this._ApplicationModule_20 = new import0.ApplicationModule(this._ApplicationRef_7);
    this._BrowserModule_21 = new import5.BrowserModule(this.parent.get(import5.BrowserModule,(null as any)));
    this._AppModule_22 = new import1.AppModule();
    return this._AppModule_22;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.ɵa)) { return this._ɵa_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import2.ɵg)) { return this._ɵg_2; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_3; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_4; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_5; }
    if ((token === import0.ɵf)) { return this._ɵf_6; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_7; }
    if ((token === import2.UrlSerializer)) { return this._UrlSerializer_8; }
    if ((token === import2.RouterOutletMap)) { return this._RouterOutletMap_9; }
    if ((token === import2.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_10; }
    if ((token === import3.LocationStrategy)) { return this._LocationStrategy_11; }
    if ((token === import3.Location)) { return this._Location_12; }
    if ((token === import0.Compiler)) { return this._Compiler_13; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_14; }
    if ((token === import2.ROUTES)) { return this._ROUTES_15; }
    if ((token === import2.Router)) { return this._Router_16; }
    if ((token === import2.RouterModule)) { return this._RouterModule_17; }
    if ((token === import4.AppRoutingModule)) { return this._AppRoutingModule_18; }
    if ((token === import3.CommonModule)) { return this._CommonModule_19; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_20; }
    if ((token === import5.BrowserModule)) { return this._BrowserModule_21; }
    if ((token === import1.AppModule)) { return this._AppModule_22; }
    if ((token === import2.ActivatedRoute)) { return this._ActivatedRoute_23; }
    if ((token === import2.NoPreloading)) { return this._NoPreloading_24; }
    if ((token === import2.PreloadingStrategy)) { return this._PreloadingStrategy_25; }
    if ((token === import2.RouterPreloader)) { return this._RouterPreloader_26; }
    if ((token === import2.PreloadAllModules)) { return this._PreloadAllModules_27; }
    if ((token === import2.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_28; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_29; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_30; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_31; }
    if ((token === import0.APP_ID)) { return this._APP_ID_32; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_33; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_34; }
    if ((token === import5.DomSanitizer)) { return this._DomSanitizer_35; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_36; }
    if ((token === import5.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_37; }
    if ((token === import5.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_38; }
    if ((token === import5.EventManager)) { return this._EventManager_39; }
    if ((token === import5.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_40; }
    if ((token === import5.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_41; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_42; }
    if ((token === import5.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_43; }
    if ((token === import0.Testability)) { return this._Testability_44; }
    if ((token === import5.Meta)) { return this._Meta_45; }
    if ((token === import5.Title)) { return this._Title_46; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_6.ngOnDestroy();
    (this.__RouterPreloader_26 && this._RouterPreloader_26.ngOnDestroy());
    (this.__ɵDomSharedStylesHost_40 && this._ɵDomSharedStylesHost_40.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2JvdWVsbGV0dGUvZ2l0L01peHBvTHVjaExlYXJuL0FuZ3VsYXI0L0N1c3RvbS9zcmMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYm91ZWxsZXR0ZS9naXQvTWl4cG9MdWNoTGVhcm4vQW5ndWxhcjQvQ3VzdG9tL3NyYy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
