/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './home.component';
const styles_HomeComponent:any[] = ([] as any[]);
export const RenderType_HomeComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_HomeComponent,
  data: {}
}
);
export function View_HomeComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[' The Home Page']))
  ]
  ,(null as any),(null as any));
}
function View_HomeComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent)),
    import0.ɵdid(49152,(null as any),0,import1.HomeComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HomeComponentNgFactory:import0.ComponentFactory<import1.HomeComponent> = import0.ɵccf('ng-component',import1.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2JvdWVsbGV0dGUvZ2l0L01peHBvTHVjaExlYXJuL0FuZ3VsYXI0L0N1c3RvbS9zcmMvYXBwL2hvbWUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2JvdWVsbGV0dGUvZ2l0L01peHBvTHVjaExlYXJuL0FuZ3VsYXI0L0N1c3RvbS9zcmMvYXBwL2hvbWUuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYm91ZWxsZXR0ZS9naXQvTWl4cG9MdWNoTGVhcm4vQW5ndWxhcjQvQ3VzdG9tL3NyYy9hcHAvaG9tZS5jb21wb25lbnQudHMuSG9tZUNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvYm91ZWxsZXR0ZS9naXQvTWl4cG9MdWNoTGVhcm4vQW5ndWxhcjQvQ3VzdG9tL3NyYy9hcHAvaG9tZS5jb21wb25lbnQudHMuSG9tZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT4gVGhlIEhvbWUgUGFnZTwvaDE+IiwiPG5nLWNvbXBvbmVudD48L25nLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFBSTs7Ozs7O0lDQUo7Z0JBQUE7Ozs7In0=
